list_background_team = ['biology & earth science',
 'technical',
 'it',
 'business',
 'medical',
 'chemistry',
 'physics',
 'other',
 'arts',
 'social sciences',
 'entrepreneurship',
 'mathematics',
 'law']

 list_degree_team = ['biology & earth science',
 'technical',
 'it',
 'business',
 'medical',
 'chemistry',
 'physics',
 'other',
 'arts',
 'social sciences',
 'entrepreneurship',
 'mathematics',
 'law']

 list_industries = ['health',
 'fintech',
 'energy',
 'telecom',
 'enterprise software',
 'sports',
 'semiconductors',
 'security',
 'legal',
 'music',
 'media',
 'marketing',
 'transportation',
 'food',
 'kids',
 'robotics',
 'real estate',
 'education',
 'wellness beauty',
 'home living',
 'fashion',
 'hosting',
 'jobs recruitment',
 'gaming',
 'event tech',
 'travel']

 list_income_streams = ['commission', 'subscription', 'selling own inventory', 'advertising']

list_technologies = ['big data',
 'computer vision',
 'deep tech',
 '3d technology',
 'hardware',
 'machine learning',
 'artificial intelligence',
 'iot internetofthings',
 'nanotech',
 'recognition technology',
 'mobile app',
 'connected device',
 'deep learning',
 'virtual reality',
 'autonomous & sensor tech',
 'blockchain',
 'augmented reality',
 'ai',
 'quantum technologies',
 'natural language processing']

 list_investors_name = ['Agoranov', 'European Innovation Council', 'Eurostars SME programme',
       'Kima Ventures', 'Idinvest Partners', 'Elaia Partners',
       'It Translation', 'Sofimac Innovation', 'Crédit Agricole',
       'Femmes Business Angels', 'Seventure Partners', 'GO Capital',
       'Sofinnova Partners', 'Turenne Capital', 'Demeter Partners',
       'Incubateur Paris And Co', 'CapDecisif Management', 'Starquest Capital',
       'Business Angels Des Grandes Ecoles', 'CEA Investissement', 'Partech',
       'Angelsquare', 'Omnes Venture Capital', 'BNP Paribas', 'Kurma Partners',
       'XAnge', 'EIT InnoEnergy', 'Région Sud Investissement', 'Finovam',
       'CM-CIC Innovation', 'Sofimac Régions', "Cap Innov'Est", 'Kreaxi',
       'Newfund', 'Supernova Invest']

list_investor_type = ['fund',
 'investor',
 'corporate',
 'government_nonprofit',
 'service_provider',
 'company',
 'crowdfunding',
 'workspace']

 list_tags = ['investing',
 'risk management',
 'biotechnology',
 'sustainable development goals',
 'core sustainable impact',
 'biomass',
 'agritech',
 'alternative protein',
 'affordable and clean energy (#7)',
 'climate action (#13)',
 'imaging technology',
 'eic',
 'nanoscopy',
 'microscopy',
 'good health and well-being (#3)',
 'non-invasive',
 'health care',
 'medical device',
 'femtech',
 'vivatech2019',
 'medical / healthcare',
 'touchscreen',
 'human computer interaction',
 'gesture recognition',
 'platform',
 'arts & culture',
 'search engine',
 'printing',
 'clean water and sanitation (#6)',
 'testing',
 'polymer',
 'repair',
 'medical',
 'chemistry',
 'health diagnostics',
 'life science',
 'neuroscience',
 'power',
 'radio',
 'network',
 'lte',
 '4g',
 'banking',
 'streaming',
 'communication',
 'monitoring',
 'sharing economy',
 'community',
 'mapping',
 'navigation',
 'video',
 'drones',
 'packaging and containers',
 'system engineering',
 'telecommunications',
 'space tech',
 'electronic switching solutions',
 'electronic micro-relays',
 'recycling',
 'waste reduction',
 'appliances',
 'display screen glass',
 'light-emitting diode',
 '3d architecture',
 'circuit',
 'pharmacy',
 'therapies',
 'drug development',
 'directory',
 'saas',
 'cybersecurity',
 'adtech',
 'industrial tech software',
 'alzheimers disease',
 'parkinson',
 'silicon',
 'analytics',
 'voice recognition',
 'api',
 'speech recognition',
 'behavioral analysis',
 'emotions',
 'facial recognition',
 'notification',
 'retail',
 'vision',
 'prevention',
 'molecular',
 'music',
 'audio',
 'satellites',
 'nanosatellites',
 'cubesats',
 'messaging',
 'collaboration',
 'real time',
 'app',
 'wearable',
 'predictive analytics',
 'chat',
 'eyewear',
 'enterprise resource planning',
 'freemium',
 'pharmaceutical',
 'drug discovery',
 'statistical methods',
 'mechanics',
 'research and development',
 'healthcare',
 'back office',
 'automated process',
 'automated technology',
 'embedding technology',
 'tool',
 'compliance',
 'security',
 'regtech compliance',
 'genetics',
 'tissue engineering',
 'information technology',
 'channel',
 'commerce',
 'omnichannel',
 'developer tools',
 'merchant tools',
 'architecture',
 'android',
 'alcohol',
 'cooking tech',
 'wine and spirits',
 'delivery',
 'warehousing',
 'logistic',
 'autonomous vehicles',
 'automotive',
 'robotic',
 'pay per result',
 'iot',
 'iiot',
 'industrial iot',
 'industry 4.0',
 'predictive maintenance',
 'smart building',
 'smart city',
 'real estate',
 'industrial automation',
 'control systems',
 'programmable logic controller',
 'cooling tech',
 'cost management',
 'electrical installations',
 'optimization',
 'edge computing',
 'cloud computing',
 'refrigeration',
 'thermal engineering',
 'sustainable cities and communities (#11)',
 'user behavior',
 'dna',
 'simulation',
 'training',
 'planning',
 'organs',
 'healthcare industry',
 'surgery',
 'disease',
 'therapeutics',
 'ophthalmology',
 'sensor',
 'epilepsy',
 'health',
 'clothes',
 'neurology',
 'missionfrenchtech',
 'apparel',
 'health platform',
 'smart tech',
 'computer',
 'fraud detection',
 'blood',
 'brain',
 'biopharma',
 'medical diagnostics',
 'industrial lasers',
 'laser communication',
 'photonic',
 'protein',
 'macro-nutrients',
 'call',
 'virtual assistant',
 'customer service',
 'call center',
 'customer management',
 'phone',
 'customer support',
 'ultrasound',
 'cardiology',
 'heart disease',
 'physician',
 'screening',
 'disorders',
 'oncology',
 'genome engineering',
 'cancer',
 'security solutions',
 'security and safety',
 'privacy protection',
 'surveillance',
 'aviation & aerospace',
 'defense',
 'aerospace',
 'public safety',
 'statistics',
 'data analytics',
 'business intelligence',
 'social',
 'open source',
 'seo',
 'social media',
 'semantic ',
 'semantic search',
 'farming',
 'cyber security',
 'data mining',
 'cryptography',
 'solar energy',
 'natural resources',
 'product',
 'electron microscopy',
 'microscope',
 'branding',
 'threat intelligence',
 'anti fraud',
 'software',
 'fraud',
 'chatbot',
 'luxury',
 'monetization',
 'organisation',
 'alternative data',
 'image recognition',
 'neural networks',
 'app development',
 'hospital',
 'diabetes',
 'personal health',
 'precision agriculture',
 'satellite imagery',
 'satellite tech',
 'forestry',
 'asset management',
 'capital market',
 'bitcoin',
 'chemical',
 'industrial technology',
 'material technology',
 'epigenetics',
 'rna',
 'sequencing',
 'acoustics',
 'sound technology',
 'speaker',
 'clinical trials',
 'authentification',
 'intellectual property',
 'intelligent systems',
 'document management',
 'insurance',
 'cognitive',
 'insurtech',
 'game development',
 'children',
 'fraud management',
 'financial service',
 'innovation management',
 'sleeping',
 'activities',
 'space',
 'lead generation',
 'industry innovation and infrastructure (#9)',
 'smart home',
 'industrial safety',
 'pathology',
 'trauma',
 'regenerative medicine',
 'city',
 'storage',
 'battery',
 'verification',
 'certification',
 'environment',
 'co2',
 'fermentation',
 'trading',
 'remote sensing',
 'geopositioning',
 'identity management',
 'marine',
 'scientific',
 'hydrogen',
 'internet of things',
 'supply chain management',
 'fuel',
 'machine',
 'database',
 'optical technology',
 'research',
 'wellness',
 'nutrition',
 'skin',
 'microbiology',
 'dermatology',
 'skin care',
 'mechanical solutions',
 'protection',
 'processing',
 'laser technology',
 'semiconductor',
 'laser',
 'pesticides',
 'crop protection',
 'bluetooth',
 'electromagnetic',
 'spectroscopy',
 'military',
 'civil',
 'therapy',
 'immune system',
 'advertising',
 'social network',
 'microfluidics',
 'user experience',
 'nanotechnology',
 'test and measurement',
 'stroke',
 'moving services',
 'computing',
 'decentralised applications',
 'dapp',
 'ethereum',
 'chemical engineering',
 'product research',
 'innovation radar',
 'algae',
 'outside tech',
 'medical imaging',
 'treatment',
 'biological',
 'inflammatory diseases',
 'clinical',
 'ft 1000',
 'energy saving',
 'consumer electronics',
 'organic',
 'lithium ion batteries',
 'agriculture',
 'biopesticides',
 'biochemical',
 'techscale200',
 'stationery',
 'chip',
 'consumer goods',
 'sustainable packaging',
 'process',
 'technology',
 'ethics',
 'zero hunger (#2)',
 'reading',
 'literacy',
 'teaching',
 'reading apps',
 'quality education (#4)',
 'visualization',
 'water heating',
 'cryptocurrencies',
 'wallet',
 'search',
 'biodegradable',
 'robotic process automation',
 'electro optics',
 'terahertz technologies',
 'quantum cascade laser',
 'diode multipliers',
 'cobots',
 'non-invasive surgery',
 'assessment',
 'primary production',
 'veterinary',
 'spectrometry',
 'recruitment',
 'adventure',
 'metrology',
 'heating',
 'well-being',
 'environmental consulting',
 'medical technology',
 'isensing & robotics',
 'agricultural technology',
 'content',
 'electric vehicle',
 'safety',
 'driverless car',
 'parking',
 'bus',
 'entertainment',
 'mobility',
 'predictive intelligence',
 'lending',
 'healthcare tech',
 'cancer therapies',
 'biomedical',
 'personalisation',
 'headphones',
 'service industry',
 'comparison',
 'modeling',
 'prediction',
 'medical research',
 'radiology',
 'quantum computing',
 'commercial',
 'biomaterials',
 'textile',
 'patient care',
 'shopping',
 '3d printing',
 'order management',
 'neuromorphic chips',
 'vision systems',
 'neuromorphic vision systems',
 'neuromorphic vision',
 'security surveillance',
 'edge processing',
 'matchmaking',
 'career',
 'on-demand services',
 'performance management',
 'nanotechnologies',
 'road safety',
 'consulting services',
 'creating',
 'deal comparison',
 'photo',
 'human resources',
 'decision making',
 'hr',
 'recruiting',
 'pollution',
 'autoimmune',
 'metabolism',
 'gastroenterology',
 'publisher tools',
 'cloud storage',
 'backup',
 'cloud services',
 'infrastructure services',
 'car',
 'eco friendly',
 'electric',
 'engineering services',
 'utilities',
 'oil & gas',
 'cleaning',
 'cleaning services',
 'conversational ai',
 'encryption',
 'cross platform',
 'data protection',
 'neuro stimulation',
 'chronic disease',
 'pain relief',
 'digital health',
 'patient engagement',
 'mooc',
 'medical systems',
 'surgeons',
 'on-demand',
 'biopolymers',
 'cargo',
 'time management',
 'cargo tracking',
 'network security',
 'biofuel',
 'ecologically friendly',
 'plant',
 'astronomy',
 'retail tech',
 'in-store retail tech',
 'obesity',
 'vaccines',
 'livestock',
 'administration',
 'contract management',
 'disability',
 'exoskeleton',
 'reduced inequalities (#10)',
 'fleet management',
 'connected car',
 'vehicle',
 'plant protection',
 'microelectronics',
 'machinery manufacturing',
 'care',
 'knowledge management',
 'laboratories',
 'infection',
 'reputation',
 'health supplements',
 'insect',
 'novel farming',
 'animal feed',
 'aquaculture',
 'pet food',
 'news & magazines',
 'allergy',
 'hosting',
 'inventory management',
 'mobile device',
 'presentation',
 'fabless manufacturing',
 'law enforcement',
 'law',
 'contract',
 'prospects',
 'pumps',
 'organic ai',
 'information services',
 'airplanes',
 'traffic',
 'biology',
 'medicine',
 'life below water (#14)',
 'facility management',
 'geolocation',
 'processor',
 'preparation',
 'kits',
 'sensor analytics',
 'application processors',
 'signals',
 'monoclonal antibodies',
 'business analytics',
 'digital twin',
 'buyers',
 'outdoor',
 'tracking',
 'inkjet printing',
 'photonic integrated circuits',
 'integrated lasers',
 'optical communication',
 'lidar',
 'precision medicine',
 'elderly care',
 'senior care',
 'synthetic biology',
 'cannabis',
 'respiratory',
 'medical & healthcare',
 'tourism',
 'talent',
 'crowdsourcing',
 'product management',
 'health insurance',
 'life insurance',
 'influencer marketing',
 'equity research',
 'swimming',
 'smart device',
 'water treatment',
 'sharing',
 'project management',
 'file sharing',
 'bpm',
 'coding',
 'workflow',
 'freelancers',
 'gig economy',
 'freelance',
 'web design',
 'agency',
 'doctor',
 'healthcare services',
 'automotive cybersecurity',
 'smart grid',
 'pension',
 'personal finance',
 'natural disaster',
 'cloud security',
 'guide',
 'customization',
 'energy efficiency',
 'decoration',
 'furniture',
 'interior design',
 'targeting',
 'reward',
 'travel',
 'loyalty program',
 'payment',
 'lawyer',
 'notary',
 'leisure',
 'booking',
 'event management',
 'meeting management',
 'partners',
 'multisport',
 'club',
 'football',
 'tennis',
 'network management',
 'sport',
 'sports clubs',
 'footwear',
 'crowdfunding',
 'food',
 'beverage',
 'crm',
 'data provider',
 'esport',
 'point of sale',
 'etf',
 'portfolio management',
 'clustering',
 'ride sharing',
 'e-bike',
 'weather forecasting',
 'life on land (#15)',
 'coach',
 'environment solutions',
 'business development',
 'conversion rate optimisation',
 'video marketing',
 'advisory',
 'content management',
 'machinery',
 'renting',
 'rental',
 'home improvement',
 'sports activity and performance',
 'restaurant',
 'carbon emissions',
 'home maintenance',
 'parenting',
 'recipes',
 'gift',
 'workspace',
 'groceries',
 'cooking',
 'ecological',
 'meal kits',
 'direct-to-consumer',
 'healthy food',
 'responsible consumption and production (#12)',
 'restaurant reservation',
 'accommodation',
 'home security',
 'face recognition',
 'discount',
 'restaurant tech',
 'staffing',
 'staffing agency',
 'data integration',
 'process technologies',
 'tailor',
 'conversion',
 'testimonials',
 'ab testing',
 'net promoter score',
 'producer',
 'notes',
 'travel &amp; expense management',
 'spend management',
 'charging technology',
 'reporting',
 'see cost management',
 'financial management',
 'mobile commerce',
 'wind energy',
 'hearing',
 'ivd',
 'horseriding',
 'pet',
 'pricing',
 '5g',
 'publishing',
 'governance',
 'govtech',
 'paas',
 'speech to text',
 'object recognition',
 'inspection',
 'lenses',
 'caregiving',
 'healthtech',
 'ingredient',
 'nutrition solution',
 'pleasure',
 'superfood',
 'meat substitutes',
 'vitamin',
 'pipes',
 'indoor navigation',
 'cigarettes',
 'running',
 'gardening',
 'herbal medicine',
 'food processing',
 'energy providers',
 'turbine',
 'smart watch',
 'local search',
 'wholesale',
 'alarm',
 'anti money laundering',
 'bike',
 'modular',
 'healthcare products',
 'natural health products',
 'agtech',
 'startupamsterdam2020',
 'plastic',
 'travel & tourism',
 'peer-to-peer',
 'boat',
 'audit',
 'transaction',
 'irrigation',
 'text analytics',
 'feedback',
 'e-learning',
 'adaptive learning',
 'telematics',
 'molecular biology',
 'money management',
 'box',
 'kid',
 'office space',
 'breeding',
 'cloud data services',
 'survey',
 'adherent french tech one',
 'fish',
 'server',
 'wildlife',
 'prototype']




